### ISSUE TITLE
shoud we change the repository name?

### ISSUE THREAD

**Issue by takasehideki** [toppers/hakoniwa-ros2sim#3]
今さらで申し訳ないのですが，リポジトリ名を変えたくなってきました．ROS 2特化なのでそれを明記したいという意図です．

候補：
- hakoniwa-ros2-simulator: 安直に ros -> ros2
- hakoniwa-ros2sim: ちょっと短くなってかっこいい？

変更箇所は把握できたので実作業は高瀬のほうで請け負います．
https://github.com/toppers/hakoniwa-ros-multiplay には影響ないはずです．
@tmori どう思われますか？

**Comment by esm-tmori** [comment]
はい，大丈夫です．後者の方がかっこいいですね．

ちなみに，hakoniwa-ros-multiplay から submodule で参照してますが，リポジトリ名変更するだけなら影響ない感じですかね？

**Comment by takasehideki** [comment]
では後者に変更します！

そうかここにありましたね,,, 内部的にURLを読み替えてくれるのでただちに影響は無いですが，そのうちこちらも修正します！
https://github.com/toppers/hakoniwa-ros-multiplay/blob/main/.gitmodules
